import type { AdminUser, AssignmentItem, ContentItem, PipelineStage } from "@/components/admin/types";

export const adminUsers: AdminUser[] = [
  {
    id: "usr_001",
    name: "Elena Vasquez",
    email: "elena@acme.io",
    region: "USA",
    companyName: "Acme Innovations LLC",
    companyType: "LLC",
    status: "active",
    servicePlan: "Scale",
    services: ["Formation", "Bookkeeping", "Tax", "Compliance"],
    quickBooksStatus: "connected",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Meera Patel",
    escalationOwner: "Nikhil Rao",
    nextSlaDueAt: "2026-03-04T14:00:00Z",
    complianceDueAt: "2026-03-20T00:00:00Z",
    lastActivityAt: "2026-03-03T08:20:00Z",
  },
  {
    id: "usr_002",
    name: "Kenji Tanaka",
    email: "kenji@northbridge.co",
    region: "UK",
    companyName: "Northbridge Labs Ltd",
    companyType: "Ltd",
    status: "awaiting_docs",
    servicePlan: "Growth",
    services: ["Bookkeeping", "Compliance"],
    quickBooksStatus: "token_expired",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Ritika Shah",
    escalationOwner: "Nikhil Rao",
    nextSlaDueAt: "2026-03-03T17:30:00Z",
    complianceDueAt: "2026-03-12T00:00:00Z",
    lastActivityAt: "2026-03-02T11:10:00Z",
  },
  {
    id: "usr_003",
    name: "Priya Sinha",
    email: "priya@fluxpay.ai",
    region: "Singapore",
    companyName: "FluxPay Pte Ltd",
    companyType: "Pte Ltd",
    status: "active",
    servicePlan: "Scale",
    services: ["Formation", "Bookkeeping", "Tax"],
    quickBooksStatus: "connected",
    accountOwner: "Daniel Roy",
    assignedAdmin: "Meera Patel",
    escalationOwner: "Ananya Verma",
    nextSlaDueAt: "2026-03-05T10:30:00Z",
    complianceDueAt: "2026-03-18T00:00:00Z",
    lastActivityAt: "2026-03-03T05:15:00Z",
  },
  {
    id: "usr_004",
    name: "Omar Khalid",
    email: "omar@desertgrid.ae",
    region: "UAE",
    companyName: "DesertGrid FZ LLC",
    companyType: "LLC",
    status: "compliance_risk",
    servicePlan: "Growth",
    services: ["Bookkeeping", "Compliance"],
    quickBooksStatus: "sync_error",
    accountOwner: "Daniel Roy",
    assignedAdmin: "Ritika Shah",
    escalationOwner: "Ananya Verma",
    nextSlaDueAt: "2026-03-03T13:00:00Z",
    complianceDueAt: "2026-03-07T00:00:00Z",
    lastActivityAt: "2026-03-01T16:45:00Z",
  },
  {
    id: "usr_005",
    name: "Rohan Mehta",
    email: "rohan@jetledger.in",
    region: "India",
    companyName: "JetLedger Technologies Pvt Ltd",
    companyType: "C-Corp",
    status: "lead",
    servicePlan: "Starter",
    services: ["Formation"],
    quickBooksStatus: "disconnected",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Kabir Nair",
    escalationOwner: "Nikhil Rao",
    nextSlaDueAt: "2026-03-06T09:00:00Z",
    complianceDueAt: "2026-03-30T00:00:00Z",
    lastActivityAt: "2026-03-02T07:40:00Z",
  },
  {
    id: "usr_006",
    name: "Sophie de Vries",
    email: "sophie@harborlytics.nl",
    region: "Netherlands",
    companyName: "HarborLytics BV",
    companyType: "C-Corp",
    status: "paused",
    servicePlan: "Starter",
    services: ["Bookkeeping"],
    quickBooksStatus: "disconnected",
    accountOwner: "Daniel Roy",
    assignedAdmin: "Kabir Nair",
    escalationOwner: "Ananya Verma",
    nextSlaDueAt: "2026-03-10T12:00:00Z",
    complianceDueAt: "2026-04-01T00:00:00Z",
    lastActivityAt: "2026-02-26T10:15:00Z",
  },
  {
    id: "usr_007",
    name: "Ava Carter",
    email: "ava@northpeak.com",
    region: "Australia",
    companyName: "NorthPeak Advisory Pty",
    companyType: "Ltd",
    status: "active",
    servicePlan: "Growth",
    services: ["Bookkeeping", "Tax"],
    quickBooksStatus: "connected",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Meera Patel",
    escalationOwner: "Nikhil Rao",
    nextSlaDueAt: "2026-03-04T08:45:00Z",
    complianceDueAt: "2026-03-22T00:00:00Z",
    lastActivityAt: "2026-03-03T07:05:00Z",
  },
  {
    id: "usr_008",
    name: "Liam Brooks",
    email: "liam@stratacore.us",
    region: "USA",
    companyName: "StrataCore Inc",
    companyType: "C-Corp",
    status: "closed",
    servicePlan: "Starter",
    services: ["Formation"],
    quickBooksStatus: "disconnected",
    accountOwner: "Daniel Roy",
    assignedAdmin: "Ritika Shah",
    escalationOwner: "Ananya Verma",
    nextSlaDueAt: "2026-03-20T18:00:00Z",
    complianceDueAt: "2026-04-15T00:00:00Z",
    lastActivityAt: "2026-02-18T09:30:00Z",
  },
];

export const assignmentQueue: AssignmentItem[] = [
  {
    id: "asg_001",
    clientId: "usr_002",
    clientName: "Northbridge Labs Ltd",
    title: "Collect Q1 bookkeeping source documents",
    category: "bookkeeping",
    status: "awaiting_client",
    priority: "high",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Ritika Shah",
    escalationOwner: "Nikhil Rao",
    slaDueAt: "2026-03-03T17:30:00Z",
  },
  {
    id: "asg_002",
    clientId: "usr_004",
    clientName: "DesertGrid FZ LLC",
    title: "Resolve QuickBooks sync failure on bills",
    category: "bookkeeping",
    status: "overdue",
    priority: "critical",
    accountOwner: "Daniel Roy",
    assignedAdmin: "Ritika Shah",
    escalationOwner: "Ananya Verma",
    slaDueAt: "2026-03-02T15:00:00Z",
  },
  {
    id: "asg_003",
    clientId: "usr_003",
    clientName: "FluxPay Pte Ltd",
    title: "Prepare monthly management P&L review pack",
    category: "tax",
    status: "in_progress",
    priority: "medium",
    accountOwner: "Daniel Roy",
    assignedAdmin: "Meera Patel",
    escalationOwner: "Ananya Verma",
    slaDueAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "asg_004",
    clientId: "usr_005",
    clientName: "JetLedger Technologies Pvt Ltd",
    title: "Onboarding call and entity setup checklist",
    category: "onboarding",
    status: "not_started",
    priority: "high",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Kabir Nair",
    escalationOwner: "Nikhil Rao",
    slaDueAt: "2026-03-06T09:00:00Z",
  },
  {
    id: "asg_005",
    clientId: "usr_001",
    clientName: "Acme Innovations LLC",
    title: "File Delaware annual report",
    category: "compliance",
    status: "in_progress",
    priority: "high",
    accountOwner: "Ari Sharma",
    assignedAdmin: "Meera Patel",
    escalationOwner: "Nikhil Rao",
    slaDueAt: "2026-03-08T17:00:00Z",
  },
];

export const contentQueue: ContentItem[] = [
  {
    id: "cnt_001",
    type: "blog",
    title: "US Sales Tax Nexus: 2026 Compliance Checklist",
    slug: "us-sales-tax-nexus-2026-checklist",
    region: "USA",
    stage: "review",
    seoScore: 74,
    owner: "Anjali (Content)",
    updatedAt: "2026-03-03T07:50:00Z",
  },
  {
    id: "cnt_002",
    type: "service",
    title: "USA Bookkeeping Service Page Refresh",
    slug: "usa-bookkeeping",
    region: "USA",
    stage: "legal_review",
    seoScore: 81,
    owner: "Raghav (SEO)",
    updatedAt: "2026-03-02T14:20:00Z",
  },
  {
    id: "cnt_003",
    type: "blog",
    title: "UAE Corporate Tax Filing Timeline",
    slug: "uae-corporate-tax-filing-timeline",
    region: "UAE",
    stage: "scheduled",
    seoScore: 88,
    owner: "Anjali (Content)",
    updatedAt: "2026-03-01T09:25:00Z",
    publishAt: "2026-03-06T06:30:00Z",
  },
  {
    id: "cnt_004",
    type: "service",
    title: "Singapore Tax Compliance Service",
    slug: "singapore-tax-compliance",
    region: "Singapore",
    stage: "published",
    seoScore: 92,
    owner: "Raghav (SEO)",
    updatedAt: "2026-02-28T11:05:00Z",
  },
  {
    id: "cnt_005",
    type: "blog",
    title: "Netherlands BV vs Branch: Founder Guide",
    slug: "netherlands-bv-vs-branch-guide",
    region: "Netherlands",
    stage: "draft",
    seoScore: 61,
    owner: "Maya (Editor)",
    updatedAt: "2026-03-03T03:10:00Z",
  },
  {
    id: "cnt_006",
    type: "service",
    title: "Global CFO Advisory Landing",
    slug: "global-cfo-advisory",
    region: "Global",
    stage: "approved",
    seoScore: 85,
    owner: "Maya (Editor)",
    updatedAt: "2026-03-02T10:35:00Z",
  },
];

export const pipelineStages: PipelineStage[] = [
  { key: "new_signup", label: "New Signups", count: 18, colorClass: "bg-blue-100 text-blue-700" },
  { key: "onboarding_pending", label: "Onboarding Pending", count: 11, colorClass: "bg-amber-100 text-amber-700" },
  { key: "docs_pending", label: "Docs Pending", count: 9, colorClass: "bg-violet-100 text-violet-700" },
  { key: "active", label: "Active Accounts", count: 74, colorClass: "bg-emerald-100 text-emerald-700" },
  { key: "at_risk", label: "At Risk", count: 6, colorClass: "bg-red-100 text-red-700" },
];
